### ISSUE TITLE
Trouble opening windows executables

### ISSUE THREAD

**Issue by rraafays** [RaafatTurki/hex.nvim#12]
I like to manually patch my games to fit my monitor ratio of 4:3 then run those patched files through proton, I wanted to switch from using ghex to using your tool because I already use nvim for everything else.

Whenever I open any exe files I get the following for example when opening tekken..

`xxd: /away/plant/Steam/steamapps/common/TEKKEN\ 7/TEKKEN\ 7.exe: No such file or directory`

**Comment by rraafays** [comment]
I should also add that whenever I manually use xxd -g 1 -u, I get the correct output

**Comment by rraafays** [comment]
Upon further testing it seems to be only when there are spaces in the path despite being escaped properly

**Comment by RaafatTurki** [comment]
thanks! new update fixes this

**Comment by rraafays** [comment]
thank you so much! ive been wanting to use your plugin to modify windows games to run in 4:3 aspect ratio without copying and renaming and i finally can thanks to this update :-)

**Comment by RaafatTurki** [comment]
@rraafays as a fellow reverse engineering enthusiast, I'm curios.
What resources did you read/watch to learn about that specific trick?

**Comment by rraafays** [comment]
i started with this https://www.wsgf.org/article/common-hex-values but honestly a lot of modern games will actually render the whole resolution regardless of aspect ratio and require some kind of edit to remove black bar letter or pillar boxing. finding which of these black box values to edit is a bit more specific to each game but theres a big community on that same website i linked you dedicated to discovering these patches :-)
