### ISSUE TITLE
vim.lsp.buf.server_ready is deprecated :help deprecated This feature will be removed in Nvim version 0.10.0

### ISSUE THREAD

**Issue by Pagliacii** [RaafatTurki/hex.nvim#13]
https://github.com/RaafatTurki/hex.nvim/blob/d47b87d49b870e2170e992fa6301fc08c9590388/lua/hex/utils.lua#L16C26-L16C26

**Comment by RaafatTurki** [comment]
new update no longer uses it, thanks!
