### ISSUE TITLE
DAP UI integration?

### ISSUE THREAD

**Issue by rohit-kumar-j** [RaafatTurki/hex.nvim#15]
I'm not exactly sure how hex editors work. Is this a compiled view or can this also be dynamic view? Is there a way to connect to dap-ui and view the editor update the memory in real time?

Like a floating window, but in neovim:
<img src="https://github.com/RaafatTurki/hex.nvim/assets/37873142/c906ccf2-d6b3-4e3e-ac7d-943bac282b4b" width =600px>

Ref: Video from 22:16 https://youtu.be/T4CjOB0y9nI?feature=shared

**Comment by RaafatTurki** [comment]
Such an interesting usecase!

AFAIK DAP clients (the debugger underneath) attaches to a running process and changes live memory values.
I'm unsure if this is the correct way to implement this but I think developing this feature require 2 essential parts:

- a method to reliably read the memory of the DAP-attached-process
- a performant way to re-read said memory everytime DAP UI changes a value

And I'm unsure on how to go about the 1st part

**Comment by rohit-kumar-j** [comment]
For the first part, 

I think nvim-dap has not yet integrated this: https://github.com/mfussenegger/nvim-dap/issues/331.
However vimspector has something [similar](https://asciinema.org/a/esEncAxP45CJmo8Em1sQtxRYe) (Although this is a work in progress)

**Comment by RaafatTurki** [comment]
Hmm I see
Is this a `codelldb` only feature or are there other DAP adapters that provide something similar?

**Comment by rohit-kumar-j** [comment]
I don't think such a feature is specific to lldb, but as of now it has been implemented in vimspector for lldb. 
[Cpp-tools](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(gdb-via--vscode-cpptools)) is the other one that I know of, they have merged something like [this directly into vscode](https://github.com/microsoft/vscode/pull/125737) as well.

**Comment by RaafatTurki** [comment]
hmm, as interesting as it is.
I don't have the knowledge to implement such capability into the plugin.
I'll say it's out of scope however a PR or a working draft would be a good starting point and are welcome.
