### ISSUE TITLE
Binary Executable breaks on Write Back

### ISSUE THREAD

**Issue by AlexZoe** [RaafatTurki/hex.nvim#18]
## Overview 

Opening a binary file and trying to save it after using `:HexToggle` breaks the executable.

The problem stems from the binary being opened as a regular file, since the plugin cannot determine that the file is a binary due to missing file extension and not being opened with the `-b` flag.

From the [VIM docs](https://neovim.io/doc/user/usr_23.html#23.3), this will likely break the file due to wrong handling.

This is likely a user error since the flag should be provided when opening the file but (some) users likely don't know about this behavior.

## Proposed Fix

Set the buffer as "binary" when calling `dump_to_hex`.

```
  vim.bo.bin = true
```

I can prepare a PR for this if you'd like.

### Prepare Binary

Compile the following content with `gcc -o run main.c`.

``` C
#include <stdio.h>

int main() {
  printf("hello\n");
  return 0;
}
```

Executing the binary prints "hello", as expected.

### Save Binary

1. Open the binary with `nvim run`
2. Call `:HexToggle` (hexdump content still correct)
3. Save with `:w`

The binary is broken after step 3.
Trying to execute the binary now gives the output

```C
Segmentation fault (core dumped)
```

**Comment by RaafatTurki** [comment]
Thanks for your thoroughness!
As you said this is user error but it still falls on the plugin to prevent such error paths.

Your suggestion is decent however I'm in the process of a complete rewrite of this plugin in order to iron out some rough edges like this one.

In the meantime feel free to PR the fix!

**Comment by AlexZoe** [comment]
I see. 

Do you have a timeline for the rewrite?

Will this be part of this repo or a separate one?

**Comment by RaafatTurki** [comment]
The rewrite is basically a separate plugin that utilizes hex.nvim as a "view mode" for buffers that are hex viewable.

And it's already [written](https://github.com/RaafatTurki/view.nvim) as are the edits for hex.nvim (locally).

The new hex.nvim will be a branch in here.
