### ISSUE TITLE
wierd string at first load

### ISSUE THREAD

**Issue by aca** [RaafatTurki/hex.nvim#2]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/50316549/211990085-5e2eed4c-d365-4481-8fa9-b19457f6e3b7.png">

**Comment by RaafatTurki** [comment]
where is that printing exactly?
also could you check if it's still occurring since I've updated possibly related code.

**Comment by RaafatTurki** [comment]
closing, feel free to reopen if the issue persists!
