### ISSUE TITLE
Invalid plugin spec

### ISSUE THREAD

**Issue by NewNork** [RaafatTurki/hex.nvim#21]
I know, this is not the lazy.nvim help line, but I can't get this plugin to work. I always receive 

`Invalid plugin spec {
  assemble = <function 1>,
  config = {
    assemble_cmd = "xxd -r",
    dump_cmd = "xxd -g 1 -u",
    is_file_binary_post_read = <function 2>,
    is_file_binary_pre_read = <function 3>
  },
  dump = <function 4>,
  setup = <function 5>,
  toggle = <function 6>
}`

Setup is as follows:
*init.lua*
`require("user.lazy")`

*lua/user/lazy.lua*
the usual lazy.nvim setup with import of `"user.plugins"`

*lua/user/plugins/init.lua*
`return {
  ...
  "RaafatTurki/hex.nvim"
}`

*lua/user/pluginx/hex.lua*
as from this repo, except first line, with reads now
`local u = require("user.plugins.hex.utils")`

*lua/user/plugins/hex/utils.lua*
as from this repo

Sorry for the dump question, I'm fairly new to nvim, lazy and lua in general, but I can't see anything wrong. Any idea? Or could someone shed some light on the rather short installation instructions in README.md?

**Comment by RaafatTurki** [comment]
hmm, the lazy.nvim spec for hex is
```lua
{
  "RaafatTurki/hex.nvim",
  config = function()
    require 'hex'.setup {}
  end
}
```
if you want to set your plugins using the [multi-file structure](https://github.com/folke/lazy.nvim?tab=readme-ov-file#-structuring-your-plugins) you can take a look at my config:
- [lazy.nvim setup](https://github.com/RaafatTurki/venom/blob/663e8bc5b015a5b7684971386141c16c8e7d2f57/lua/core/lazy.lua)
- [hex.nvim setup](https://github.com/RaafatTurki/venom/blob/663e8bc5b015a5b7684971386141c16c8e7d2f57/lua/plugins/hex.lua)
