### ISSUE TITLE
not seem to work

### ISSUE THREAD

**Issue by wuc9521** [RaafatTurki/hex.nvim#5]
I used ":HexDump" and it says "already dumped " but nothing seems to have changed.
I'm new to nvim so I don't know how to handle.

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/89457423/232012357-99ff23a7-1ce3-4f22-b171-6b73475cf834.png">

**Comment by martin-braun** [comment]
Try to toggle with `:HexToggle`, does this work?

**Comment by RaafatTurki** [comment]
Hi @Naturalifica could you provide your nvim version (`nvim -v`) and does this behavior occur on any file (try a `.png`)?

**Comment by wuc9521** [comment]
Thanks a lot, `:HexToggle` worked ! 

> Try to toggle with `:HexToggle`, does this work?

**Comment by Naturalifica** [comment]
my nvim version is 0.8.3 and this happened on a `.img` file

> Try to toggle with `:HexToggle`, does this work?

**Comment by wuc9521** [comment]
> Hi @Naturalifica could you provide your nvim version (`nvim -v`) and does this behavior occur on any file (try a `.png`)?

my nvim version is 0.8.3 and this happened on a .img file

**Comment by RaafatTurki** [comment]
This should be fixed, `.img` files auto dump on my end normally.
feel free to re-open this issue with a sample file if the issue persists
